package common;

public enum MessageType {
	MSG_STOP,
	
	MSG_DRIVE_TIME,
	MSG_DRIVE_DISTANCE,
	
	MSG_SCOOP_TIME,
	MSG_SCOOP_DISTANCE,
	
	MSG_DEPTH_TIME,
	MSG_DEPTH_DISTANCE,
	
	MSG_BUCKET_TIME,
	MSG_BUCKET_DISTANCE,
	
	MSG_STOP_TIME,
	
	MSG_STATE_OFF,
	MSG_STATE_ROTATE_TO_MARKER,
	MSG_STATE_DRIVE_TO_DIG,
	MSG_STATE_COLLECT_MATERIAL,
	MSG_STATE_DRIVE_TO_BIN,
	MSG_STATE_RAISE_BUCKET,
	MSG_STATE_LOWER_BUCKET,
	
	MSG_STATE_TELEOP_CONTROL
}
