MAX_SPEED = 1.0
MIN_SPEED = -1.0

DRIVE_SPEED = 0.75
SCOOP_SPEED = 0.75
DEPTH_SPEED = 0.05
WINCH_SPEED = 1.00

LEFT_DRIVE_DEVICE_ID = 1
RIGHT_DRIVE_DEVICE_ID = 2
COLLECTOR_DEPTH_DEVICE_ID = 3
COLLECTOR_SCOOPS_DEVICE_ID = 4
WINCH_DEVICE_ID = 5

LOOP_DELAY_TIME = 0.010

K_PERCENT_VBUS = 0
K_CURRENT = 1
K_SPEED = 2
K_POSITION = 3
K_VOLTAGE = 4
K_FOLLOWER = 5
K_MOTION_PROFILE = 6
K_MOTION_MAGIC = 7

HOST = "localhost"
PORT = 9999