import Logger
import numpy as np

SENSOR_BOARD_PORT = "/dev/arduino"
MOTOR_BOARD_PORT = "/dev/ttyUSB0"
CONTROL_STATION_IP = "192.168.0.100"
CONTROL_STATION_PORT = 11000
CAMERA_PORT1 = 11001

USING_MOTOR_BOARD = False
USING_SENSOR_BOARD = True
USING_NETWORK_COMM = True
USING_JOYSTICK = False

MAX_SPEED = 1.0
MIN_SPEED = -1.0

DRIVE_SPEED = 0.75
SCOOP_SPEED = 0.75
DEPTH_SPEED = 0.05
WINCH_SPEED = 1.00

LEFT_DRIVE_DEVICE_ID = 1
RIGHT_DRIVE_DEVICE_ID = 2
COLLECTOR_DEPTH_DEVICE_ID = 3
COLLECTOR_SCOOPS_DEVICE_ID = 4
WINCH_DEVICE_ID = 5

LOOP_DELAY_TIME = 0.050

HOST = "localhost"
PORT = 9999

ON_LINUX = True

LOG_CRITICAL = 1
LOG_SEVERE = 2
LOG_MODERATE = 3
LOG_LOW = 4
LOG_DEBUG = 5

#Camera Constants (inches)
TF_CAM_ROBOT_POSITION_X = 36;
TF_CAM_ROBOT_POSITION_Y = -26;
TF_CAM_ROBOT_POSITION_Z = 14;
TF_CAM_ROBOT_POSITION = np.matrix([[TF_CAM_ROBOT_POSITION_X], [TF_CAM_ROBOT_POSITION_Y], [TF_CAM_ROBOT_POSITION_Z]]);

TF_TARGET_POSITION_X = 0;
TF_TARGET_POSITION_Y = 0;
TF_TARGET_POSITION_Z = 200;
TF_TARGET_POSITION = np.matrix([[TF_TARGET_POSITION_X], [TF_TARGET_POSITION_Y], [TF_TARGET_POSITION_Z]]);	
TF_TARGET_ORIENTATION = np.matrix([[1, 0, 0],[0, 1, 0], [0, 0, 1]]); 



LOGGER = Logger.Logger(LOG_DEBUG)