MAX_SPEED = 1.0
MIN_SPEED = -1.0

DRIVE_SPEED = 0.75
SCOOP_SPEED = 0.75

LEFT_DRIVE_DEVICE_ID = 1
RIGHT_DRIVE_DEVICE_ID = 2
COLLECTOR_DEPTH_DEVICE_ID = 3
COLLECTOR_SCOOPS_DEVICE_ID = 4
WINCH_DEVICE_ID = 5

LOOP_DELAY_TIME = 0.010
